// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEkPTH9kJG7E5gsVcXtOVhEhRrzRbYfl8',
    appId: '1:351742470263:web:c3fd9f9fdf315fa1e53e72',
    messagingSenderId: '351742470263',
    projectId: 'print-firebase',
    authDomain: 'print-firebase.firebaseapp.com',
    databaseURL: 'https://print-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'print-firebase.appspot.com',
    measurementId: 'G-75N6QV0FJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmAoY4OWeVmt9_gYw-2GFBUxvQ-Pjg4RU',
    appId: '1:351742470263:android:1ca55718a33b2a4ce53e72',
    messagingSenderId: '351742470263',
    projectId: 'print-firebase',
    databaseURL: 'https://print-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'print-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhK-g4DTaC6Z6SvEt-gUuCmbQDrwK3lUs',
    appId: '1:351742470263:ios:58caabeb21038900e53e72',
    messagingSenderId: '351742470263',
    projectId: 'print-firebase',
    databaseURL: 'https://print-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'print-firebase.appspot.com',
    iosBundleId: 'com.example.sneakerShoesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhK-g4DTaC6Z6SvEt-gUuCmbQDrwK3lUs',
    appId: '1:351742470263:ios:58caabeb21038900e53e72',
    messagingSenderId: '351742470263',
    projectId: 'print-firebase',
    databaseURL: 'https://print-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'print-firebase.appspot.com',
    iosBundleId: 'com.example.sneakerShoesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEkPTH9kJG7E5gsVcXtOVhEhRrzRbYfl8',
    appId: '1:351742470263:web:a391585811d51fb8e53e72',
    messagingSenderId: '351742470263',
    projectId: 'print-firebase',
    authDomain: 'print-firebase.firebaseapp.com',
    databaseURL: 'https://print-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'print-firebase.appspot.com',
    measurementId: 'G-5QZBTJ385H',
  );
}
